from enum import Enum

class TaskStatus(Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class PipelineStage(Enum):
    INITIALIZING = "INITIALIZING"
    DOWNLOADING = "DOWNLOADING"
    PROCESSING_INVENTORY = "PROCESSING_INVENTORY"
    PROCESSING_SLA = "PROCESSING_SLA"
    PROCESSING_INCIDENTS = "PROCESSING_INCIDENTS"
    GENERATING_CHARTS = "GENERATING_CHARTS"
    GENERATING_PPT = "GENERATING_PPT"
    CLEANUP = "CLEANUP"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
